---
title: "Heavy inextensible strings in the Schwarzschild geometry"
author: "Robin Hankin"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library("deSolve")
```

The light inextensible string functional was

$$
\int_{p_1}^{p_2}\left(\frac{\left(r'\right)^2}{1-2M/r} + r^2\right)^\frac{1}{2}d\phi
$$

But now we use a Lagrange multiplier:

$$
\int_{p_1}^{p_2}\left[\left(\frac{\left(r'\right)^2}{1-2M/r} + r^2\right)^\frac{1}{2}
+\lambda\left(\frac{\left(r'\right)^2}{1-2M/r} + r^2\right)^\frac{1}{2}
\left(1-\sqrt{1-2M/r}\right)
\right]d\phi
$$

that is, miminizing the potential energy subject to a (proper) length
constraint.  Simplifying: 

$$
\int_{p_1}^{p_2}\left(\frac{\left(r'\right)^2}{1-2M/r} +
r^2\right)^\frac{1}{2} \left(1+\lambda(1-\sqrt{1-2M/r})\right) d\phi
$$




```
EulerEquations[ 
  Sqrt[r[\[Phi]]^2 + 
     r'[\[Phi]]^2/(1 - 2*M/r[\[Phi]])]*(1 + \[Lambda]*(1 - 
        Sqrt[1 - 2*M/r[\[Phi]]])), r[\[Phi]], \[Phi]] // FullSimplify
```

Now define the  second derivative from Euler's equation:

```{r definerdashdash}
rdashdash <- function(r,rdash,lambda,M=1/2){
    x <- sqrt(1-2*M/r)
    return(
    (M*(4+lambda*(4-3*x))*r^2 + (-1+lambda*(-1+x))*r^3 + M*(3 + lambda*(3-2*x))*rdash^2 +
     2*r*(M^2*(-2+lambda*(-2+x)) + (-1+lambda*(-1+x))*rdash^2))/((-1+lambda*(-1+x))*r*(-2*M+r))
    )
}
```


```{r useode}
string <- function(r0,lambda=0,angles=seq(from = 0, to = 0.5, by = 0.01)){

    parameters <- c(lambda = lambda, M = 1/2)
    state <- c(r = r0, rdash = 0)
    times <- angles

    Lorenz <- function(t, state, parameters){
        with(as.list(c(state, parameters)), {
            dr <- rdash
            drdash <- rdashdash(r, rdash, lambda, M)
            list(c(dr, drdash))
        })
    }
    
    out <- ode(y = state, times = times, func = Lorenz, parms = parameters)
    
    
    phi <- out[,1]
    r <- out[,2]
    
    return(cbind(r*cos(phi),r*sin(phi)))
}
```


```{r plotstringsonepointtwo}

dist <- 1.2
lambda <- seq(from = -0.05, to = -1.7, by = -0.1)
f <- approxfun(
    c(0,-0.1,-0.2,-0.5, -0.7, -1,  -1.4,     -1.6,-1.7),
    c(2.4,2.4, 2.1,1.5,   1.5, 1.1,  0.63, 0.3,0)
)

plot(lambda,f(lambda))

size <- 2
par(pty="s")
plot(NA,type="n",asp=1,xlim=c(-size,size),ylim=c(-size,size))
th <- seq(from=0,to=2*pi,len=100)
points(cos(th),sin(th),type='l')  # event horizon

for(l in lambda){
    points(string(r0 = dist, lambda = l, angles = seq(0,f(l),0.01)), type = 'l')
}

segments(dist,0,4,0)
docolour <- function(lambda,...){
    points(string(r0 = dist, lambda = lambda, angles=seq(0,f(lambda),0.01)), type='l', lwd=3, ...)
}
#docolour(-0.05,col='blue')
#docolour(-0.7,col='green')
#docolour(-1.4,col='red')
points(1.2,0,pch=16)
```


```{r plotstringsonepointzerofour}

dist <- 1.04
lambda <- seq(from = 0, to = -1, by = -0.1)

f <- approxfun(
    c(0,-0.1,-0.2,-0.5, -0.7, -1,  -1.4,     -1.6,-1.7),
    c(2.4,2.4, 2.1,1.5,   1.5, 0.5,  0.63, 0.3,0)
)

plot(lambda,f(lambda))

size <- 2
par(pty="s")
plot(NA,type="n",asp=1,xlim=c(-size,size),ylim=c(-size,size))
th <- seq(from=0,to=2*pi,len=100)
points(cos(th),sin(th),type='l')  # event horizon

for(l in lambda){
    points(string(r0 = dist, lambda = l, angles = seq(0,f(l),0.01)), type = 'l')
}

segments(dist,0,4,0)
docolour <- function(lambda,...){
    points(string(r0 = dist, lambda = lambda, angles=seq(0,f(lambda),0.01)), type='l', lwd=3, ...)
}
docolour(0,col='red')
docolour(-1,col='blue')
points(dist,0,pch=16)
```
